name: Purge Camo Cache

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kevincobain2000/action-camo-purge@v1
